### ISSUE TITLE
Upgrade and Implement Modern CSS & HTML Practices

### ISSUE THREAD

**Issue by SameerJS6** [sarmadhamdani02/WebGames#17]
#### Issue Description

The aim is to upgrade our project's CSS and HTML practices to align with modern web development standards. This will involve optimizing code readability and reducing redundancy. The goal is to make our codebase more maintainable and accessible, especially for beginners.

#### Proposed Changes

We plan to refactor existing CSS and HTML code to adopt modern practices. For instance, we will transform the following code snippet:

```css
.main-content {
  overflow: hidden;
  height: calc(100vh - 50px);
  width: 100vw;
  background-color: white;
  display: flex;
  align-items: start;
  justify-content: start;
  flex-direction: row;
  flex-wrap: wrap;
  gap: 2rem;
  padding: 30px;
}
```

Into this more concise and modern version:

```css 
.main-content {
  gap: 2rem;
  display: flex;
  padding: 2rem;
  flex-wrap: wrap;
  background-color: white;
}
```

We'll leverage CSS Variables, new units, and other techniques to enhance code readability and streamline our styles.

#### Expected Benefits

- Improved codebase maintainability
- Enhanced readability, especially for newcomers
- Reduction in code redundancy
- Get rid of unnecessary code
- Alignment with current best practices in web development

#### Discussion

Feel free to share your thoughts and suggestions regarding the proposed modernization of our CSS and HTML practices.

#### Related Resources

- [Link to documentation on CSS Variables](https://developer.mozilla.org/en-US/docs/Web/CSS/--*)
- [Link to article on using new CSS units](https://css-tricks.com/the-lengths-of-css/)
- [The problems with viewport units](https://youtu.be/veEqYQlfNx8)
